### ISSUE TITLE
Add a quickstart to the README

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/SSSOM#11]
The docs are great but you have to read a lot to get the gist

I suggest in the README adding an example table or two, e.g

|subject_id|predicate_id|object_id|match_type|subject_label|object_label^M|
|---|---|---|---|---|---|
|HP:0009124|skos:exactMatch|MP:0000003|Lexical|Abnormal adipose tissue morphology|abnormal adipose tissue morphology^M|
|HP:0008551|skos:exactMatch|MP:0000018|Lexical|Microtia|small ears^M|
|HP:0000411|skos:exactMatch|MP:0000021|Lexical|Protruding ear|prominent ears^M|

**Comment by matentzn** [comment]
Made a stab at that.

**Comment by matentzn** [comment]
https://github.com/OBOFoundry/SSSOM/blob/master/README.md
