### ISSUE TITLE
feedback solicited on blog post

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/SSSOM#29]
not sure the best way to do this, here is a pdf from the blog post scheduled to go out in a couple of days:
[Edit Post ‹ Monkeying around with OWL — WordPress.com.pdf](https://github.com/OBOFoundry/SSSOM/files/5087754/Edit.Post.Monkeying.around.with.OWL.WordPress.com.pdf)

It will end up here:
https://douroucouli.wordpress.com/2020/08/18/a-simple-standard-for-sharing-mappings/

**Comment by mcourtot** [comment]
sorry PDF didn't work - see screenshot. Maybe copy/paste text here?

<img width="1054" alt="Screenshot 2020-08-18 at 07 55 30" src="https://user-images.githubusercontent.com/2214135/90480542-49b8a300-e128-11ea-84b3-8165a72ce92a.png">

**Comment by matentzn** [comment]
or google docs. Thank you @cmungall !!

**Comment by cmungall** [comment]
it's out now!

(sorry it came out earlier, I forgot it was set to UTC time..)
